import type { TopicQuiz } from "./types";

// Türevin Tanımı ve Temel Kuralları (AYT) — pilot question bank.
// Correct answers deliberately spread across A–E.
const quiz: TopicQuiz = {
  slug: "turevin-tanimi",
  questions: [
    {
      id: "turevin-tanimi-01",
      difficulty: "Kolay",
      prompt: String.raw`$f(x) = x^2$ fonksiyonu için $\lim\limits_{h\to 0}\dfrac{f(3+h)-f(3)}{h}$ limitinin değeri kaçtır?`,
      options: ["$3$", "$6$", "$9$", "$12$", "$18$"],
      correct: 1,
      solution: [
        String.raw`Verilen limit, türevin tanımıdır: $\lim\limits_{h\to 0}\dfrac{f(3+h)-f(3)}{h} = f'(3)$.`,
        String.raw`$f(x)=x^2$ için $f'(x)=2x$ olur.`,
        String.raw`$f'(3) = 2\cdot 3 = 6$.`,
      ],
      answer: String.raw`$f'(3)=6$`,
    },
    {
      id: "turevin-tanimi-02",
      difficulty: "Kolay",
      prompt: String.raw`$f(x) = x^3 - 2x$ eğrisinin $x=1$ apsisli noktasındaki teğetinin eğimi kaçtır?`,
      options: ["$-1$", "$0$", "$1$", "$2$", "$3$"],
      correct: 2,
      solution: [
        String.raw`Teğetin eğimi, o noktadaki türev değeridir: $m = f'(1)$.`,
        String.raw`$f'(x) = 3x^2 - 2$.`,
        String.raw`$f'(1) = 3\cdot 1 - 2 = 1$.`,
      ],
      answer: String.raw`$m = 1$`,
    },
    {
      id: "turevin-tanimi-03",
      difficulty: "Orta",
      prompt: String.raw`$f$ türevlenebilir bir fonksiyon ve $f'(a) = 4$ olduğuna göre, $\lim\limits_{h\to 0}\dfrac{f(a+3h)-f(a)}{h}$ limitinin değeri kaçtır?`,
      options: ["$3$", "$4$", "$7$", "$12$", "$16$"],
      correct: 3,
      solution: [
        String.raw`Limiti türev tanımına benzetmek için pay ve paydayı düzenleyelim: $\dfrac{f(a+3h)-f(a)}{h} = 3\cdot\dfrac{f(a+3h)-f(a)}{3h}$.`,
        String.raw`$u = 3h$ dersek $h\to 0$ iken $u\to 0$ olur: $3\cdot\lim\limits_{u\to 0}\dfrac{f(a+u)-f(a)}{u} = 3f'(a)$.`,
        String.raw`$3f'(a) = 3\cdot 4 = 12$.`,
      ],
      answer: String.raw`$3f'(a) = 12$`,
    },
    {
      id: "turevin-tanimi-04",
      difficulty: "Orta",
      prompt: String.raw`$f(x) = |x-2|$ fonksiyonunun $x = 2$ noktasındaki durumu için aşağıdakilerden hangisi doğrudur?`,
      options: [
        "Süreklidir ve türevlenebilir.",
        "Süreklidir fakat türevlenemez.",
        "Sürekli değildir fakat türevlenebilir.",
        "Ne süreklidir ne de türevlenebilir.",
        "Yalnızca sağdan türevlenebilir.",
      ],
      correct: 1,
      solution: [
        String.raw`Süreklilik: $\lim\limits_{x\to 2}|x-2| = 0 = f(2)$ olduğundan $f$, $x=2$'de süreklidir.`,
        String.raw`Soldan türev: $x<2$ için $f(x)=2-x$, dolayısıyla $f'_-(2) = -1$.`,
        String.raw`Sağdan türev: $x>2$ için $f(x)=x-2$, dolayısıyla $f'_+(2) = +1$.`,
        String.raw`$f'_-(2) \neq f'_+(2)$ olduğundan $x=2$'de türev yoktur (grafikte sivri nokta).`,
      ],
      answer: String.raw`Süreklidir fakat türevlenemez.`,
    },
    {
      id: "turevin-tanimi-05",
      difficulty: "Orta",
      prompt: String.raw`$f(x) = 3x^4 - 2x^2 + 5x - 7$ olduğuna göre $f'(-1)$ kaçtır?`,
      options: ["$-21$", "$-11$", "$-3$", "$3$", "$13$"],
      correct: 2,
      solution: [
        String.raw`Kuvvet kuralıyla türev alalım: $f'(x) = 12x^3 - 4x + 5$.`,
        String.raw`$x=-1$ yazalım: $f'(-1) = 12(-1)^3 - 4(-1) + 5$.`,
        String.raw`$f'(-1) = -12 + 4 + 5 = -3$.`,
      ],
      answer: String.raw`$f'(-1) = -3$`,
    },
    {
      id: "turevin-tanimi-06",
      difficulty: "Orta",
      prompt: String.raw`$y = x^2 + 3x$ parabolünün hangi noktasındaki teğeti $y = 5x + 1$ doğrusuna paraleldir?`,
      options: ["$(0,\\,0)$", "$(1,\\,5)$", "$(2,\\,10)$", "$(5,\\,40)$", "$(1,\\,4)$"],
      correct: 4,
      solution: [
        String.raw`Paralel doğruların eğimleri eşittir; $y=5x+1$ doğrusunun eğimi $5$'tir.`,
        String.raw`$y' = 2x + 3$ olduğundan $2x+3 = 5 \Rightarrow x = 1$.`,
        String.raw`$x=1$ için $y = 1 + 3 = 4$; teğet noktası $(1,\,4)$.`,
      ],
      answer: String.raw`$(1,\,4)$`,
    },
    {
      id: "turevin-tanimi-07",
      difficulty: "Zor",
      prompt: String.raw`$f(x) = \begin{cases} ax^2 + b, & x \le 1 \\ 4x, & x > 1 \end{cases}$ fonksiyonu $x=1$ noktasında türevlenebilir olduğuna göre, $a\cdot b$ çarpımı kaçtır?`,
      options: ["$4$", "$2$", "$6$", "$8$", "$16$"],
      correct: 0,
      solution: [
        String.raw`Türevlenebilirlik için önce türevler eşleşmeli: soldan $(ax^2+b)' = 2ax \Rightarrow 2a$, sağdan $(4x)' = 4$. Buradan $2a = 4 \Rightarrow a = 2$.`,
        String.raw`Türevlenebilen fonksiyon sürekli de olmalıdır: $a\cdot 1 + b = 4\cdot 1 \Rightarrow a + b = 4$.`,
        String.raw`$a=2$ için $b = 2$ bulunur.`,
        String.raw`$a\cdot b = 2\cdot 2 = 4$.`,
      ],
      answer: String.raw`$a\cdot b = 4$`,
    },
    {
      id: "turevin-tanimi-08",
      difficulty: "Zor",
      prompt: String.raw`Bir hareketlinin konumu $s(t) = t^3 - 6t^2 + 9t$ (metre, $t$ saniye) ile veriliyor. Hareketlinin anlık hızı hangi anlarda sıfırdır?`,
      options: [
        String.raw`Yalnız $t=1$`,
        String.raw`Yalnız $t=3$`,
        String.raw`$t=0$ ve $t=3$`,
        String.raw`$t=1$ ve $t=3$`,
        String.raw`$t=2$ ve $t=3$`,
      ],
      correct: 3,
      solution: [
        String.raw`Anlık hız, konumun türevidir: $v(t) = s'(t) = 3t^2 - 12t + 9$.`,
        String.raw`$v(t) = 0$ için: $3t^2 - 12t + 9 = 0 \Rightarrow 3(t^2 - 4t + 3) = 0$.`,
        String.raw`Çarpanlara ayıralım: $3(t-1)(t-3) = 0 \Rightarrow t = 1$ veya $t = 3$.`,
      ],
      answer: String.raw`$t=1$ ve $t=3$ anlarında hız sıfırdır.`,
    },
    {
      id: "turevin-tanimi-09",
      difficulty: "Orta",
      prompt: "$f$ fonksiyonu $x=3$ noktasında türevlenebilir olup $$\\lim_{x\\to 3}\\frac{f(x)-f(3)}{x^{2}-9}=2$$ eşitliği sağlanmaktadır. Buna göre $f'(3)$ kaçtır?",
      options: ["6", "12", "18", "24", "36"],
      correct: 1,
      solution: ["Paydayı çarpanlarına ayır: $x^{2}-9=(x-3)(x+3)$.", "İfadeyi türev tanımına uygun parçala: $\\dfrac{f(x)-f(3)}{x^{2}-9}=\\dfrac{f(x)-f(3)}{x-3}\\cdot\\dfrac{1}{x+3}$.", "$x\\to 3$ için ilk çarpan tanım gereği $f'(3)$'e, ikinci çarpan $\\dfrac{1}{3+3}=\\dfrac{1}{6}$'ya gider.", "Böylece $f'(3)\\cdot\\dfrac{1}{6}=2 \\Rightarrow f'(3)=12$."],
      answer: "12",
    },
    {
      id: "turevin-tanimi-10",
      difficulty: "Orta",
      prompt: "$$f(x)=\\begin{cases}ax^{2}+3,& x\\le 2\\\\[2pt] bx+1,& x>2\\end{cases}$$ fonksiyonu $x=2$ noktasında türevlenebilirdir. Buna göre $a+b$ kaçtır?",
      options: ["$\\dfrac{3}{2}$", "$2$", "$\\dfrac{9}{4}$", "$\\dfrac{5}{2}$", "$3$"],
      correct: 3,
      solution: ["**Süreklilik** ($x=2$): soldan $a\\cdot 2^{2}+3=4a+3$, sağdan $2b+1$. Eşitle: $4a+3=2b+1 \\Rightarrow b=2a+1$.", "**Türev eşitliği:** soldan türev $f'_-(x)=2ax \\Rightarrow f'_-(2)=4a$; sağdan türev $f'_+(x)=b \\Rightarrow f'_+(2)=b$. Eşitle: $b=4a$.", "İki bağıntıyı çöz: $4a=2a+1 \\Rightarrow a=\\dfrac{1}{2}$, dolayısıyla $b=4\\cdot\\dfrac{1}{2}=2$.", "İstenen: $a+b=\\dfrac{1}{2}+2=\\dfrac{5}{2}$."],
      answer: "$\\dfrac{5}{2}$",
    },
    {
      id: "turevin-tanimi-11",
      difficulty: "Orta",
      prompt: "$g(x)=x^{2}+\\lvert x-2\\rvert$ fonksiyonu için $g'_+(2)$ sağdan türevi ile $g'_-(2)$ soldan türevi tanımlanıyor. Buna göre $g'_+(2)-g'_-(2)$ farkı kaçtır?",
      options: ["$2$", "$1$", "$0$", "$-1$", "$4$"],
      correct: 0,
      solution: ["$x>2$ için $\\lvert x-2\\rvert=x-2$, yani $g(x)=x^{2}+x-2$ ve $g'(x)=2x+1$; buradan $g'_+(2)=2\\cdot 2+1=5$.", "$x<2$ için $\\lvert x-2\\rvert=2-x$, yani $g(x)=x^{2}-x+2$ ve $g'(x)=2x-1$; buradan $g'_-(2)=2\\cdot 2-1=3$.", "Soldan ve sağdan türev farklı olduğundan $g$, $x=2$'de türevlenemez (köşe noktası).", "İstenen fark: $g'_+(2)-g'_-(2)=5-3=2$."],
      answer: "$2$",
    },
    {
      id: "turevin-tanimi-12",
      difficulty: "Zor",
      prompt: "Türevlenebilir bir $f$ fonksiyonu için $f(2)=5$ ve $f'(2)=3$ veriliyor. Buna göre $$\\lim_{h\\to 0}\\frac{f(2+3h)-f(2-h)}{h}$$ limitinin değeri kaçtır?",
      options: ["$6$", "$9$", "$12$", "$15$", "$18$"],
      correct: 2,
      solution: ["Payı, $f(2)$ ekleyip çıkararak iki türev tanımına böl: $f(2+3h)-f(2-h)=\\big[f(2+3h)-f(2)\\big]+\\big[f(2)-f(2-h)\\big]$.", "İlk parça: $\\dfrac{f(2+3h)-f(2)}{h}=3\\cdot\\dfrac{f(2+3h)-f(2)}{3h}\\to 3f'(2)$.", "İkinci parça: $\\dfrac{f(2)-f(2-h)}{h}=\\dfrac{f(2-h)-f(2)}{-h}\\to f'(2)$.", "Toplam: $3f'(2)+f'(2)=4f'(2)=4\\cdot 3=12$."],
      answer: "$12$",
    },
    {
      id: "turevin-tanimi-13",
      difficulty: "Orta",
      prompt: "$f(x)=\\begin{cases}x^{2}+ax,& x\\le 1\\\\[2pt] b\\ln x+3,& x>1\\end{cases}$ fonksiyonu $x=1$ noktasında türevlenebilirdir. Buna göre $a\\cdot b$ çarpımı kaçtır?",
      options: ["$8$", "$10$", "$12$", "$15$", "$18$"],
      correct: 0,
      solution: ["**Süreklilik** ($x=1$): soldan $1+a$, sağdan $b\\ln 1+3=3$. Eşitle: $1+a=3\\Rightarrow a=2$.", "**Türev eşitliği:** soldan türev $f'_-(x)=2x+a\\Rightarrow f'_-(1)=2+a$; sağdan türev $f'_+(x)=\\dfrac{b}{x}\\Rightarrow f'_+(1)=b$. Eşitle: $b=2+a=2+2=4$.", "Bulunanlar: $a=2$, $b=4$ (her iki koşul da sağlanır).", "İstenen çarpım: $a\\cdot b=2\\cdot 4=8$."],
      answer: "$8$",
    },
    {
      id: "turevin-tanimi-14",
      difficulty: "Kolay",
      prompt: "$f$ ve $g$ türevlenebilir fonksiyonlar olup $f(x)=x^{2}\\,g(x)$ biçiminde tanımlanmıştır. $g(2)=3$ ve $g'(2)=-1$ veriliyor. Buna göre $f'(2)$ kaçtır?",
      options: ["$4$", "$6$", "$8$", "$10$", "$12$"],
      correct: 2,
      solution: ["Çarpım kuralı: $f'(x)=\\big(x^{2}\\big)'g(x)+x^{2}g'(x)=2x\\,g(x)+x^{2}g'(x)$.", "$x=2$ koy: $f'(2)=2\\cdot 2\\cdot g(2)+2^{2}\\cdot g'(2)=4\\cdot 3+4\\cdot(-1)$.", "Hesapla: $f'(2)=12-4=8$."],
      answer: "$8$",
    },
  ],
};

export default quiz;
